[package]
name = "shotgun"
version = "1.1.4"
authors = ["Dan Elkouby <streetwalkermc@gmail.com>"]

[dependencies]
getopts = "0.2"
isatty = "0.1"
libc = "0.2"
time = "0.1"

[dependencies.image]
default-features = false
version = "0.15"
features = ["png_codec"]

[dependencies.x11]
version = "2.15"
features = ["xlib", "xrandr"]
